version: '3.8'

services:
  db:
    image: postgres:15
    container_name: blockchain-monitor-db
    restart: always
    environment:
      POSTGRES_USER: alert_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto_alerts
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - blockchain-monitor-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blockchain-monitor-app
    restart: always
    environment:
      PORT: 3000
      DATABASE_URL: postgres://alert_user:password@db:5432/crypto_alerts
      EVM_RPC_URL: https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID
      JWT_SECRET: your_jwt_secret
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - blockchain-monitor-network
    volumes:
      - .:/usr/src/app

volumes:
  db_data:

networks:
  blockchain-monitor-network:
    driver: bridge
